# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('mob_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(7000000000)])),
                ('email', models.CharField(max_length=20)),
                ('passwrd', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
