# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='DOB',
            field=models.CharField(max_length=200),
        ),
    ]
