# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20160929_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='name',
            field=models.DateField(max_length=200),
        ),
    ]
