# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bus_from', models.CharField(max_length=25)),
                ('bus_to', models.CharField(max_length=25)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('no_seats', models.IntegerField()),
            ],
        ),
    ]
