# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busside', '0002_auto_20161025_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
