# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busside', '0004_auto_20161129_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='buses',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
