# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busside', '0005_auto_20161208_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buses',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
